#!/usr/bin/env python3
import socket
import sys
from datetime import datetime


def main():
    if len(sys.argv) != 2:
        print("Usage: python timeserver <port>")
        sys.exit(1)

    port = int(sys.argv[1])

    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_socket.bind(('', port))
    server_socket.listen(5)

    print(f"Сервер запущен и слушает порт {port}...")

    while True:
        client_socket, addr = server_socket.accept()
        print(f"Подключение от {addr}")

        current_time = datetime.now().strftime("%d.%m.%Y %H:%M")

        client_socket.sendall(current_time.encode('utf-8'))

        client_socket.close()
        print("Соединение с клиентом закрыто.")


if __name__ == "__main__":
    main()
