#!/usr/bin/env python3
import socket
import sys


def main():
    if len(sys.argv) != 3:
        print("Usage: python timeclient <server_ip> <port>")
        sys.exit(1)

    server_ip = sys.argv[1]
    port = int(sys.argv[2])

    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    client_socket.connect((server_ip, port))
    print(f"Подключение к серверу {server_ip}:{port}...")

    data = client_socket.recv(1024)
    print("Текущая дата и время:", data.decode('utf-8'))

    client_socket.close()
    print("Соединение с сервером закрыто.")


if __name__ == "__main__":
    main()
